---

- name: create php dirs
  file:
    path: "{{ item|safe|trim }}"
    state: directory
    owner: "{{ php_user }}"
    group: "{{ php_group }}"
    mode: 0777
    recurse: true
  changed_when: "False"
  with_items:
    - "{{ php_opt_dir }}"
    - "{{ php_config_dir }}"
    - "{{ php_config_dir }}/pool"

- name: transfer pool.d php configuration
  template:
    src: "{{ item }}"
    dest: "{{ php_config_dir }}/pool/{{ item | basename }}"
    force: true
    mode: 0777
  with_fileglob:
    - ../templates/config/pool.d/*.conf


- name: transfer php.ini php-fpm configuration
  template:
    src: config/php.ini
    dest: "{{ php_config_dir }}/php.ini"
    force: true
    mode: 0777
