---

- name: Setup group
  ansible.builtin.group:
    name: "{{ php_group }}"
    system: true

- name: Setup user
  ansible.builtin.user:
    name: "{{ php_user }}"
    system: true
    group: "{{ php_group }}"
