---
- name: Restart php
  ansible.builtin.service:
    name: Php
    state: restarted
    enabled: true

- name: Start php
  ansible.builtin.service:
    name: Php
    state: started

- name: Reload php
  ansible.builtin.service:
    name: Php
    state: reloaded
