#!/usr/bin/env bash

chmod -R 777 /var/log/
mkdir -p /var/run/php/
mkdir -p /run/php/
set -eux -o pipefail

# pull the image before so we dont first remove the container and then pull
docker pull clouddrove/php:"{{ php_version }}"

docker rm -f -v php || :

docker run -u root --net=host --rm --name=php \
	-v /var/www:/var/www:rw \
	-v /etc/ssh/ssh_config:/etc/ssh/ssh_config:rw \
	-v {{ php_config_dir }}/php.ini:/usr/local/etc/php/php.ini \
	-v {{ php_config_dir }}/pool/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf \
	-v {{ php_config_dir }}/pool/extra-config.ini:/usr/local/etc/php-fpm.d/extra-config.ini  \
	clouddrove/php:"{{ php_version }}"
