#!/usr/bin/env bash

chmod -R 777 /var/log/
mkdir -p /var/run/php/
mkdir -p /run/php/
set -eux -o pipefail

# pull the image before so we dont first remove the container and then pull
docker pull clouddrove/php:"{{ php_version }}"-fpm

docker rm -f -v php || :

docker run -u root --net=host --rm --name=php \
	-v /var/www:/var/www:rw \
	-v /etc/ssh/ssh_config:/etc/ssh/ssh_config:rw \
	-v {{ php_config_dir }}/php.ini:/usr/local/etc/php/php.ini \
	-v {{ php_config_dir }}/pool/www.conf:/usr/local/etc/php-fpm.d/www.conf \
	-v {{ php_config_dir }}/pool/upstream.conf:/usr/local/etc/php-fpm.d/upstream.conf  \
	-v {{ php_config_dir }}/pool/queue.conf:/usr/local/etc/php-fpm.d/queue.conf  \
	clouddrove/php:"{{ php_version }}"-fpm
